language: python
python:
- '3.5'
install: pip install -r requirements.txt
script:
  - make check
  - make test
notifications:
  slack:
    secure: d3pssvPgKiOofCP+cIRYlcn2Hy1Lr7qA9s8YqRxV5iM2IHpaz7pZRZmXjIATiga6FeiJorzKyeEJAbJefmVboIa76drW4yOCNj9hSjYH9yaVxINKVqi4p9Fqwm0z0zopFie3GTVVICzrMJ5nYlyCPBK6MljJpI/zGN4TfVAiwoHi0/bz8LuoTRuJS4/1VK4h8FYYrBpuTKUw8ftdUDokWBYfzaoTD24gtFKHF0m4+qOoTnkAU+v0DRgOHuPxwyQ6wIuJoqA4k2JgnO31xq9d2qmtsB0T7hEFANnwh5WBE1/0PX8PnrLCSWcC64Mpd5mfbSws2pZy5C9eiLLmKg/zJp6favye2cAceGNpeYF2IZf3xPHtlOFAQ3vYGE01iGslst1IeIZfVeOMVhk1TbYvvOEVuGN7cePUaxsJ2XQf85RtSHfUb3ra+JOMZzfLK69dzSqWBqpqCbLaKJXC9LWPNaSClT8kbodrDzYWGpPBQy528V6q4JNqsbq9mmfCZK2uu6hszrguSEk3x3O6neHEgElDWcFs27uf9Fc7wtO91clav3MT1xN8E7VoJJwvpsnPqGeDCMa0O/WQRvW7rtxUs7ChsIUl7U40clOVn1NfqYtlfJxit92nzrky4VDcLfZw2FZnW3D4rrAB+257fLLU6wpI515iwWYpBeWK1fGmLPY=
